### ISSUE TITLE
Post Message action freezes on execution, but continues successfully after killing running proces/microflow on server node

### ISSUE THREAD

**Issue by Crow74** [ako/SlackConnector#7]
The java action that posts a message to a channel on Slack freezes up when it is executed from a microflow on our test node in the Mendix cloud.

But when I go to the node metrics of the test node and kill the running microflow from the Running Now tab page, the message gets posted to Slack successfully.

Here is a detailed analysis of what happens, as far as we can see it.

When the microflow starts and the java action is executed, we see the following messages appear in the console log:

`Apr 26 12:57:46.009 - INFO - SlackConnector: postMessage: development, Test with Nick present`
`Apr 26 12:57:46.030 - INFO - SlackConnector: Using session: com.ullink.slack.simpleslackapi.impl.SlackWebSocketSessionImpl@1530ee5a, is connected: false`
`Apr 26 12:57:46.049 - INFO - SlackConnector: Reconnecting slack session`

We looked where that 'Reconnecting' log message is posted. That happens in the getSession() method, which I posted below for convenience. We have the feeling that the java method freezes at the second 'session.connect()' statement. I placed a comment behind the call.

![image](https://cloud.githubusercontent.com/assets/13252706/25432424/ab223574-2a84-11e7-8b1c-b919de0e731a.png)

As soon as we kill the microflow, the see the message is posted successfully. We see the following info messages posted to the log:

`Apr 26 13:09:27.662 - INFO - SlackConnector: Channel: development`
`Apr 26 13:09:28.569 - INFO - SlackConnector: done postingMessage`

Any help is greatly appreciated!

Best regards,
Theo Tol

**Comment by ako** [comment]
I suspect this is caused by a deadlock due to incorrect concurrency handling. I've rewritten the connector to improve concurrency.  Can you test if this solves your issues? Published as release 1.3.1 in the appstore.

**Comment by Crow74** [comment]
Hello Andrej,

I tested the changes, but unfortunately posting the message still freezes up the microflow on the server. When I go to the node metrics of the test node and kill the running microflow from the Running Now tab page, the message is not posted, which was not the case with the previous version.

One thing I have to mention (and what I should have mentioned earlier) is that I am working in Mendix 6.10.2, so I have copied all the changed .java files from the GitHub project to my own project manually because the new version is developed with Mendix 7.0.2. I hope that is not causing this issue I am having.

If there is anything I can do to help fix this issue, or if I can deliver more information, please let me know.

Best regards,
Theo Tol
